# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - dev

pool:
  name: 'Builder'

variables:
  GIT_PAT: $(gitPat)
  AZURE_PAT: $(azurePass)

name: 1.0.$(Rev:r)

steps:
  - task: CmdLine@2
    inputs:
      script: 'printf "SERVER_URL=%s\nUPDATE_VERSION_URL=%s\nUPDATE_VERSION_API=%s\n" "$SERVER_URL" "$UPDATE_VERSION_URL"  "$UPDATE_VERSION_API" > .env'
  - task: CmdLine@2
    displayName: Prebuild
    inputs:
      script: |
        cat .env
        docker build -t supermedicalchain/build-flutter --build-arg BUILD_NAME=$(BUILD_NAME) .
      workingDirectory: $(System.DefaultWorkingDirectory)
  - task: CmdLine@2
    displayName: Copy from Container
    inputs:
      script: |
        docker run --rm -v $(pwd)/build:/src/build2 supermedicalchain/build-flutter sh -c 'rm -Rf /src/build2/*  && cp -a /src/build/. /src/build2 && chmod -R 777 /src/build2'
      workingDirectory: $(System.DefaultWorkingDirectory)
  - task: mirror-git-repository-vsts-task@1
    inputs:
      sourceGitRepositoryUri: '$(Build.Repository.Uri)'
      sourceVerifySSLCertificate: false
      destinationGitRepositoryUri: 'https://github.com/sonntuet1997/medical-release'
      sourceGitRepositoryPersonalAccessToken: $(AZURE_PAT)
      destinationGitRepositoryPersonalAccessToken: $(GIT_PAT)

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'build/app/outputs/flutter-apk'
      ArtifactName: 'output'
      publishLocation: 'Container'